version: '3.7'

services:
    db:
        image: mysql
        restart: always
        entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./containers/mysql/sql:/docker-entrypoint-initdb.d/:ro
            - mysql_data:/var/lib/mysql
        
    api:
        build: ./api
        environment:
            RAILS_ENV: ${RAILS_ENV}
            DATABASE_URL: mysql2://root:${MYSQL_ROOT_PASSWORD}@db/${MYSQL_DATABASE}
            DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
        volumes:
            - ./api:/var/www/music_bingo
        ports:
            - "3000:3000"
        depends_on:
            - db

    web:
        build: ./web
        ports:
            - "4200:4200"
        volumes:
            - ./web:/app
            - /app/node_modules
        depends_on:
            - api

volumes:
    mysql_data:
