version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped
          
    api:
        build: ./api
        environment:
            RAILS_ENV: development
            DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
            DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@db/music_bingo
            DATABASE_NAME: music_bingo
            DATABASE_USER: postgres
            DATABASE_PASSWORD: changeme
            DATABASE_HOST: db
        volumes:
            - ./api:/usr/src/app
            - gem_cache:/usr/local/bundle/gems
        ports:
            - "3000:3000"
        depends_on:
            - db

    web:
        build: ./web
        ports:
          - "4200:4200"
        environment:
            SHELL: /bin/bash
            NODE_ENV: development
        volumes:
            - ./web:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        depends_on:
            - api
        entrypoint: npm start -- --poll 1
   
    redis:
        image: 'redis:alpine'
        command: redis-server
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'

volumes:
    postgres:
    gem_cache:
    node_modules:
    redis:

