version: '3.7'

services:
    db:
        image: mysql
        restart: always
        entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        
    api:
        build: ./api
        environment:
            RAILS_ENV: development
            DATABASE_URL: mysql2://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
            TEST_DATABSE_URL: mysql2://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}_test
            DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
        volumes:
            - ./api:/var/www/music_bingo
        ports:
            - "3000:3000"
        depends_on:
            - db

    web:
        build: ./web
        ports:
            - "80:80"
        depends_on:
            - api
